## IMPORT LIBRARIES

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv('Social_Network_Ads.csv')

In [3]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [5]:
df.shape


(400, 3)

In [6]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [7]:
df.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [8]:
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import StandardScaler as sc
from sklearn.neighbors import KNeighborsClassifier

In [9]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [10]:
print(x,y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [11]:
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.2,random_state=0)

In [12]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(320, 2) (80, 2) (320,) (80,)


In [13]:
model=KNeighborsClassifier()

In [14]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [15]:
y_prev=model.predict(x_test)

In [16]:
print(y_prev)

[0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 1
 0 0 0 0 1 1]


In [17]:
# model.score(y_prev.reshape(-1,1),y_test)

In [18]:
import sklearn.metrics 

In [19]:
print(sklearn.metrics.classification_report(y_prev,y_test))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88        58
           1       0.68      0.68      0.68        22

    accuracy                           0.82        80
   macro avg       0.78      0.78      0.78        80
weighted avg       0.82      0.82      0.82        80



In [20]:
print(sklearn.metrics.confusion_matrix(y_prev,y_test))

[[51  7]
 [ 7 15]]


## Confusion Matrix  Manul calculation

In [21]:
print('Truth/Recall - 0 value : 51')
print(51/58)

Truth/Recall - 0 value : 51
0.8793103448275862


In [22]:
print('Truth/Recall - 1 value : 15')
print(15/22)

Truth/Recall - 1 value : 15
0.6818181818181818


In [23]:
print('precision/predicted 0 values : 51')
print(51/58)

precision/predicted 0 values : 51
0.8793103448275862


In [24]:
print('precision/predicted 1 values : 15')
print(15/(15+7))

precision/predicted 1 values : 15
0.6818181818181818


In [25]:
y_prev.shape

(80,)

In [26]:
y_test.shape

(80,)

In [27]:
predicted_tested_values=pd.DataFrame([y_prev,y_test])

In [28]:
predicted_tested_values=predicted_tested_values.transpose()

In [29]:
predicted_tested_values.columns=['y_prev','y_test']

In [30]:
predicted_tested_values.head(15)

y_prev  y_test
0        0       0
1        0       0
2        0       0
3        0       0
4        0       0
5        0       0
6        0       0
7        1       1
8        0       0
9        0       0
10       0       0
11       0       0
12       0       0
13       1       0
14       0       0

In [31]:
predicted_tested_values.value_counts()

y_prev  y_test
0       0         51
1       1         15
0       1          7
1       0          7
dtype: int64

In [32]:
model.predict([[26,43000]])

array([0], dtype=int64)

# Choosing the Best K value

In [33]:
# error_rate=[]
# for i in range(1,40):
#     knn=KNeighborsClassifier(n_neighbors=i)
#     knn.fit(x_train,y_train)
#     y_i=knn.predict(x_test)
#     print(f'y_i{y_i} \n, y_test: {y_test}')
#     print('-'*125)
#     print(f'{np.mean(y_i!=y_test)}')

y_i[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 1 1 0 1
 0 0 0 0 1 1] 
, y_test: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
-----------------------------------------------------------------------------------------------------------------------------
0.1875
y_i[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0
 0 0 0 0 1 1] 
, y_test: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
-----------------------------------------------------------------------------------------------------------------------------
0.2125
y_i[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 

 0 0 0 0 1 1]
-----------------------------------------------------------------------------------------------------------------------------
0.15
y_i[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1
 0 0 0 0 0 1] 
, y_test: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
-----------------------------------------------------------------------------------------------------------------------------
0.125
y_i[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1
 0 0 0 0 0 1] 
, y_test: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
---------------------------------------

In [34]:
a=[1,2,3,4,5]
b=[6,7,8,9,1]

In [35]:
a!=b

True

In [36]:
iteration_value=pd.DataFrame([0 ,0, 0, 0, 0 ,1 ,0 ,1, 0 ,0 ,0 ,0, 0 ,0 ,0 ,1 ,1, 0, 1 ,1, 0 ,1 ,0 ,1 ,0 ,0 ,0 ,0 ,0 ,0, 0, 0,1, 0, 0, 0 ,0
, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
 0, 0, 0, 0, 1, 1])
test_value=pd.DataFrame(y_test)

In [37]:
np.mean(iteration_value  !=test_value)

0    0.1875
dtype: float64

In [38]:
print(iteration_value.mean())
print(test_value.mean())

0    0.3375
dtype: float64
0    0.275
dtype: float64


In [48]:
r=iteration_value.mean()*test_value.mean()
print(r)
print(f'{r/2}')

0    0.092813
dtype: float64
0    0.046406
dtype: float64


In [40]:
# len([0 ,0, 0, 0, 0 ,1 ,0 ,1, 0 ,0 ,0 ,0, 0 ,0 ,0 ,1 ,1, 0, 1 ,1, 0 ,1 ,0 ,1 ,0 ,0 ,0 ,0 ,0 ,0, 0, 0,1, 0, 0, 0 ,0
# , 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
#  0, 0, 0, 0, 1, 1])

In [41]:
# iteration_value.columns=['iteration_value']
# test_value.columns=['test_values']
# iteration_value=list(iteration_value['iteration_value'])
# # test_value=list(test_value['test_value'])


In [42]:
# print(type(test_value),type(iteration_value))

In [43]:
# test_value=list(test_value['test_values'])

In [44]:
# c=[]
# for i in range(len(iteration_value)):
#     if(iteration_value[i]!=test_value[i]):
#         c.append(1)
        

In [45]:
# v=pd.DataFrame(c)

In [46]:
# v.columns=['error_rate_list']

In [47]:
# v.mean()

In [69]:
error_rate=[]
for i in range(1,40):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train,y_train)
    y_i=knn.predict(x_test)
    print(f'y_i{y_i} \n, y_test: {y_test}')
    print('-'*125)
    print(f'{np.mean(y_i!=y_test)}')
    error_rate.append(np.mean(y_i!=y_test))
print(f'Minimum error_rate is {min(error_rate)} and index/k={error_rate.index(min(error_rate))}' )

y_i[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 1 1 0 1
 0 0 0 0 1 1] 
, y_test: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
-----------------------------------------------------------------------------------------------------------------------------
0.1875
y_i[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0
 0 0 0 0 1 1] 
, y_test: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
-----------------------------------------------------------------------------------------------------------------------------
0.2125
y_i[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 

y_i[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1
 0 0 0 0 0 1] 
, y_test: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
-----------------------------------------------------------------------------------------------------------------------------
0.15
y_i[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1
 0 0 0 0 1 1] 
, y_test: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
-----------------------------------------------------------------------------------------------------------------------------
0.125
y_i[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0

In [52]:
min(error_rate)

0.1125

In [60]:
smallest=error_rate[0]
    

In [61]:
smallest

0.1875

In [65]:
for i in range(len(error_rate)):
    if(smallest>error_rate[i]):
        print(f'{smallest>error_rate[i]}')
        smallest=error_rate[i]

True
True
True
True


In [66]:
smallest

0.1125

In [70]:
knn_model=KNeighborsClassifier(n_neighbors=10)

In [71]:
knn_model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
yknn_