In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv('Data.csv')

In [3]:
df.info

<bound method DataFrame.info of    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes>

In [4]:
df.shape

(10, 4)

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [7]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [8]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [9]:
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [10]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [11]:
x=df.iloc[:,:-1]

In [12]:
y=df.iloc[:,-1]

In [13]:
print(f"{x}\n\n{y}")

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [14]:
type(x)

pandas.core.frame.DataFrame

In [15]:
#x.dropna(axis=0,inplace=True)

In [16]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [17]:
#y.dropna(axis=0,inplace=True)

In [18]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

## TAKING CARE OF MISSING VALUES

In [19]:
df.Salary.mean()

63777.77777777778

In [20]:
#df=df.Salary.replace('NAN',1,regex=True)    

In [21]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [22]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
print(imputer)

SimpleImputer()


In [23]:
import sklearn as sk

In [24]:
dir(sk)

['__SKLEARN_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__check_build',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_distributor_init',
 '_loss',
 'base',
 'clone',
 'config_context',
 'decomposition',
 'exceptions',
 'get_config',
 'impute',
 'linear_model',
 'logger',
 'logging',
 'metrics',
 'model_selection',
 'neighbors',
 'os',
 'preprocessing',
 'random',
 'set_config',
 'setup_module',
 'show_versions',
 'svm',
 'sys',
 'utils']

In [25]:
from sklearn.impute import SimpleImputer

In [26]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [27]:
imputer

SimpleImputer()

In [28]:
imputer.fit(x.iloc[:,1:])

SimpleImputer()

In [29]:
x.iloc[:,1:]=imputer.transform(x.iloc[:,1:])

In [30]:
x

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [31]:
df1=df.copy()

In [32]:
df1

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

# ALTER MENTHOD FOR SIMPLE IMPUTER

# Treatment on overall DataFrame

In [33]:
df1.fillna(df1.mean())

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [34]:
df1

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [35]:
for i in df1.columns[df1.isnull().any(axis=0)]:
    df1[i].fillna(df1[i].mean(),inplace=True)
    


In [36]:
df1

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

# --------------------------------------------------------------------------------------------


In [37]:
for i in x.columns[x.isnull().any(axis=0)]:
    print(i)


In [38]:
x

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

# ENCODING CATEGORICAL DATA

In [39]:
x_copy=x.copy()
y_copy=y.copy()
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse=False).fit(x_copy)

In [40]:
encoder

OneHotEncoder(sparse=False)

In [41]:
x_copy=encoder.fit_transform(x_copy)

In [42]:
x_copy

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0.,

In [43]:
y_copy=encoder.inverse_transform([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,0., 0., 0., 0., 1., 0., 0.]])

In [44]:
y_copy

array([['France', 44.0, 72000.0]], dtype=object)

In [45]:
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

  # ENCODING INDEPENDENT VARIABLE
  ## COURSE ENCODING METHOD  - COLUMN TRANFORMER
  

In [46]:
import sklearn
dir(sklearn)

['__SKLEARN_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__check_build',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_distributor_init',
 '_loss',
 'base',
 'clone',
 'config_context',
 'decomposition',
 'exceptions',
 'get_config',
 'impute',
 'linear_model',
 'logger',
 'logging',
 'metrics',
 'model_selection',
 'neighbors',
 'os',
 'preprocessing',
 'random',
 'set_config',
 'setup_module',
 'show_versions',
 'svm',
 'sys',
 'utils']

In [47]:
from sklearn.compose import ColumnTransformer

In [48]:
dir(sklearn.compose)

['ColumnTransformer',
 'TransformedTargetRegressor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_column_transformer',
 '_target',
 'make_column_selector',
 'make_column_transformer']

In [49]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [50]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [0])])

In [51]:
x=ct.fit_transform(x)

In [52]:
x

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

# Standard Scaler

In [53]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# scaler.fit(x_copy)
# X_scaled = scaler.transform(x_copy)

In [54]:
# X_scaled

# ENCODING DEPENTENT VARIABLES USING (LABEL_ENCODER)

In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
dir(sklearn.preprocessing)

['Binarizer',
 'FunctionTransformer',
 'KBinsDiscretizer',
 'KernelCenterer',
 'LabelBinarizer',
 'LabelEncoder',
 'MaxAbsScaler',
 'MinMaxScaler',
 'MultiLabelBinarizer',
 'Normalizer',
 'OneHotEncoder',
 'OrdinalEncoder',
 'PolynomialFeatures',
 'PowerTransformer',
 'QuantileTransformer',
 'RobustScaler',
 'StandardScaler',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_csr_polynomial_expansion',
 '_data',
 '_discretization',
 '_encoders',
 '_function_transformer',
 '_label',
 'add_dummy_feature',
 'binarize',
 'label_binarize',
 'maxabs_scale',
 'minmax_scale',
 'normalize',
 'power_transform',
 'quantile_transform',
 'robust_scale',
 'scale']

In [57]:
lb=LabelEncoder()

In [58]:
y=lb.fit_transform(y)

In [59]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [60]:
prev=lb.inverse_transform([1,0])

In [61]:
print(prev)

['Yes' 'No']


# SPLITTING THE DATASET INTO TRAINING SET AND TEST SET

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=5)

In [64]:
x_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04]])

In [65]:
from sklearn.linear_model import LinearRegression

In [66]:
model=LinearRegression()
model.fit(x_train,y_train)
y_predict=model.predict(x_test)


In [67]:
# y_predict=model.predict([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,0., 0., 0., 0., 1., 0., 0.]])
# y_predict=int(y_predict)
# print(scaler.transform(y_predict))
# value=model.predict(scaler.transform([[-0.81649658,  1.52752523, -0.65465367, -0.33333333, -0.33333333,
#         -0.33333333, -0.33333333, -0.33333333, -0.33333333,  3.        ,
#         -0.33333333, -0.33333333, -0.33333333, -0.33333333, -0.33333333,
#         -0.33333333, -0.33333333, -0.33333333,  3.        , -0.33333333,
#         -0.33333333, -0.33333333, -0.33333333]]))

In [68]:
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [69]:
print("{0:.2f}".format( accuracy_score(y_test,y_predict.round())*100))

66.67


# FEATURE SCALING

In [70]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()


In [71]:
print(x_train)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]]


In [72]:
print(x_test)

[[1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.5e+01 5.8e+04]
 [0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]]


In [73]:
x_train[:,3:]=sc.fit_transform(x_train[:,3:])

In [74]:
x_trains=x_train

In [75]:
x_test

array([[1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04]])

In [76]:
x_test[:,3:]=sc.transform(x_test[:,3:])

In [77]:
x_tests=x_test

In [78]:
new_lr=LinearRegression()


In [79]:
new_lr

LinearRegression()

In [80]:
new_lr.fit(x_trains,y_train)

LinearRegression()

In [81]:
y_p=new_lr.predict(x_tests)

In [88]:
print("{0:.2f} %".format(accuracy_score(y_test,y_p.round())*100))

66.67 %


### WASTE 

In [107]:
from sklearn.linear_model import LogisticRegression as lor

In [108]:
model_lor = lor()


In [109]:
model_lor.fit(x_train,y_train)

LogisticRegression()

In [110]:
lor_yPredict=model.predict(x_test)
print(lor_yPredict.round())

[4. 4. 4.]


In [111]:
print(accuracy_score ( y_test,lor_yPredict.round()))

0.0


In [112]:
y_test

array([1, 1, 0])